const userRoute = require('./user')
const authRoute = require('./auth')
const roleRoute = require('./role')
const productRoute = require('./product')
const productDetailRoute = require('./productDetail')
const productConfigurationRoute = require('./productConfiguration')
const variationOptionRoute = require('./variationOption')
const variationRoute = require('./variation')
const categoryRoute = require('./category')
const categoryItemRoute = require('./categoryItem')
const blogCategoryRoute = require('./blogCategory')
const blogRoute = require('./blog')
const brandRoute = require('./brand')
const couponRoute = require('./coupon')
const orderRoute = require('./order')
const stripeRoute = require('./stripe')
const { notFound } = require('../middleware/handleError')

const initRoute = (app) => {
    app.use('/api/stripe', stripeRoute)
    app.use('/api/order', orderRoute)
    app.use('/api/coupon', couponRoute)
    app.use('/api/brand', brandRoute)
    app.use('/api/blog', blogRoute)
    app.use('/api/blog-category', blogCategoryRoute)
    app.use('/api/categories', categoryRoute)
    app.use('/api/category-item', categoryItemRoute)
    app.use('/api/products', productRoute)
    app.use('/api/variation', variationRoute)
    app.use('/api/variation-option', variationOptionRoute)
    app.use('/api/product-configuration', productConfigurationRoute)
    app.use('/api/product-detail', productDetailRoute)
    app.use('/api/users', userRoute)
    app.use('/api/role', roleRoute)
    app.use('/api/auth', authRoute)

    app.use(notFound('Page not found!'))
}

module.exports = initRoute
